# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9be0e0bfa790109f3d58f68ba13e3c1ed5aaf6900857eee55db973a9e7fd3a3d38bd6c914e2146777bd4bf2a6c52e9c8179c992b09b9fd6f66becd64a77c8cd

test:
  secret_key_base: e70d038c2e780f7526083b36bf6b11c49690d7584cab5b60a914e5d150f783303e27477409d8169fd895797dcc86727cf9d50897520555b907f49419553c080c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
